apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: krmp-d2hub-idock.9rum.cc/dev-test/repo_91c3aa4f326c #컨테이너 이미지 경로 이곳 수정
          imagePullPolicy: Always
          resources:
            requests:
              memory: 1Gi
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: upload-storage
              mountPath: "/app/uploads"
      volumes:
        - name: upload-storage
          persistentVolumeClaim:
            claimName: upload-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - port: 8080
      targetPort: 8080
